/**
 * Category: 01_FUNDAMENTALS Subcategory: 03_DEVELOPMENT Concept: 02 Topic: Declaration Files Purpose: Creating and using .d.ts files Difficulty: intermediate UseCase: libraries,type-sharing,external-code Version: TS1.0+ Compatibility: Node.js, Browsers Performance: Type checking speed Security: Type safety */

/**
 * Declaration Files - Comprehensive Guide
 * ========================================
 * 
 * 📚 WHAT: Creating and using .d.ts files
 * 💡 WHY: Provide type information for JavaScript code and enable type checking
 * 🔧 HOW: .d.ts syntax, declaration merging, @types packages
 */

// ============================================================================
// SECTION 1: WHAT ARE DECLARATION FILES
// ============================================================================

// Example 1.1: Basic Concept
// -----------------------

// Declaration files (.d.ts) contain type information without implementation
// They describe the shape of JavaScript code for TypeScript

interface DeclarationFile {
  extension: string;
  content: string;
  output: string;
}

const declFileInfo: DeclarationFile = {
  extension: ".d.ts",
  content: "Type signatures only - no implementation",
  output: "Generated by tsc or manually written"
};

// Example 1.2: Usage
// -----------------

interface DeclFileUsage {
  libraries: string;
  modules: string;
  globals: string;
}

const declFileUsage: DeclFileUsage = {
  libraries: "Provide types for JavaScript libraries",
  modules: "Describe module exports",
  globals: "Define global variables and functions"
};

// ============================================================================
// SECTION 2: CREATING DECLARATION FILES
// ============================================================================

// Example 2.1: Manual Declaration
// -----------------------------

// my-module.d.ts
declare module "my-module" {
  export function greet(name: string): string;
  export class Greeter {
    constructor(greeting: string);
    greeting: string;
    greet(name: string): string;
  }
  export default Greeter;
}

// Example 2.2: Function Declarations
// ---------------------------

declare function calculateSum(a: number, b: number): number;
declare function calculateProduct(a: number, b: number): number;

interface MathOperations {
  sum: typeof calculateSum;
  product: typeof calculateProduct;
}

// ============================================================================
// SECTION 3: DECLARATION FILE SYNTAX
// ============================================================================

// Example 3.1: Interface Declarations
// -------------------------------

interface User {
  id: number;
  name: string;
  email: string;
}

interface UserService {
  getUser(id: number): Promise<User>;
  createUser(user: Omit<User, "id">): Promise<User>;
  updateUser(id: number, user: Partial<User>): Promise<User>;
  deleteUser(id: number): Promise<void>;
}

declare const userService: UserService;

// Example 3.2: Class Declarations
// --------------------------

declare class Animal {
  constructor(name: string);
  name: string;
  speak(): string;
  static create(name: string): Animal;
}

// ============================================================================
// SECTION 4: GENERATING DECLARATION FILES
// ============================================================================

// Example 4.1: tsconfig.json Settings
// -------------------------------

interface DeclGenerationConfig {
  compilerOptions: {
    declaration: boolean;
    declarationDir: string;
    declarationMap: boolean;
    outDir: string;
  };
}

const declGenConfig: DeclGenerationConfig = {
  compilerOptions: {
    declaration: true,
    declarationDir: "./dist",
    declarationMap: true,
    outDir: "./dist"
  }
};

// Example 4.2: Output Structure
// -----------------------

interface OutputStructure {
  files: string[];
  directories: string[];
}

const outputStructure: OutputStructure = {
  files: ["index.js", "index.d.ts", "index.d.ts.map"],
  directories: ["dist", "dist/types"]
};

// ============================================================================
// SECTION 5: AMBIENT DECLARATIONS
// ============================================================================

// Example 5.1: Global Declarations
// ----------------------------

// global.d.ts
declare global {
  interface Window {
    myGlobalVar: string;
    myGlobalFunc(): void;
  }
  const MY_GLOBAL_CONST: string;
  function myGlobalFunction(): number;
}

// Example 5.2: Namespace Declarations
// ---------------------------

declare namespace MyNamespace {
  const version: string;
  function init(): void;
  class Config {
    static getInstance(): Config;
    get(key: string): string;
  }
}

// ============================================================================
// SECTION 6: MODULE DECLARATIONS
// ============================================================================

// Example 6.1: Module Augmentation
// ----------------------------

declare module "express" {
  interface Request {
    userId?: string;
    isAuthenticated?: boolean;
  }
}

declare module "*.svg" {
  const content: string;
  export default content;
}

// Example 6.2: Module Resolution
// -----------------------

declare module "custom-loader" {
  export default function loader(source: string): string;
  export interface LoaderOptions {
    debug?: boolean;
    minify?: boolean;
  }
}

// ============================================================================
// SECTION 7: USING @TYPES PACKAGES
// ============================================================================

// Example 7.1: Installing Type Definitions
// -----------------------------------

interface TypePackage {
  npm: string;
  scope: string;
  example: string;
}

const typePackage: TypePackage = {
  npm: "npm install --save-dev @types/node",
  scope: "@types/{package-name}",
  example: "@types/react, @types/lodash"
};

// Example 7.2: Type Resolution
// -----------------------

interface TypeResolution {
  node_modules: string;
  types: string;
  fallback: string;
}

const typeResolution: TypeResolution = {
  node_modules: "Check node_modules/@types",
  types: "Check package.json types field",
  fallback: "Use any if no types found"
};

// ============================================================================
// SECTION 8: DECLARATION MERGING
// ============================================================================

// Example 8.1: Interface Merging
// ----------------------------

interface Book {
  title: string;
}

interface Book {
  author: string;
}

const book: Book = {
  title: "TypeScript Guide",
  author: "Author Name"
};

// Example 8.2: Namespace Merging
// --------------------------

namespace Animals {
  export interface Dog {
    bark(): void;
  }
}

namespace Animals {
  export interface Cat {
    meow(): void;
  }
}

// ============================================================================
// SECTION 9: COMPATIBILITY
// ============================================================================

// Example 9.1: TypeScript Version Support
// ------------------------------------

interface VersionSupport {
  minimum: string;
  recommended: string;
}

const versionSupport: VersionSupport = {
  minimum: "1.0",
  recommended: "4.5 or higher"
};

// Example 9.2: Module System Support
// ------------------------------

interface ModuleSystemSupport {
  commonjs: string;
  amd: string;
  umd: string;
  esm: string;
}

const moduleSupport: ModuleSystemSupport = {
  commonjs: "Supported",
  amd: "Supported",
  umd: "Supported",
  esm: "Supported"
};

// ============================================================================
// SECTION 10: PERFORMANCE
// ============================================================================

// Example 10.1: Build Performance
// -----------------------

interface BuildPerformance {
  declaration: string;
  declarationMap: string;
}

const buildPerf: BuildPerformance = {
  declaration: "Additional compilation time",
  declarationMap: "Minimal overhead"
};

// Example 10.2: Type Checking Performance
// ---------------------------------

interface TypeCheckPerformance {
  skipLibCheck: string;
  typeRoots: string;
}

const typeCheckPerf: TypeCheckPerformance = {
  skipLibCheck: "skipLibCheck speeds up type checking",
  typeRoots: "Specify typeRoots to limit search"
};

// ============================================================================
// SECTION 11: SECURITY
// ============================================================================

// Example 11.1: Type Safety
// ---------------------

interface TypeSafety {
  any: string;
  unknown: string;
  strict: string;
}

const typeSafety: TypeSafety = {
  any: "Avoid using 'any' - loses type safety",
  unknown: "Use 'unknown' for external data",
  strict: "Enable strict mode for better safety"
};

// ============================================================================
// SECTION 12: TESTING DECLARATIONS
// ============================================================================

// Example 12.1: Validation
// ---------------------

interface DeclarationValidation {
  syntax: boolean;
  exports: boolean;
  types: boolean;
}

const declValidation: DeclarationValidation = {
  syntax: "Validate .d.ts syntax",
  exports: "Check all exports present",
  types: "Test type resolution"
};

// ============================================================================
// SECTION 13: ALTERNATIVES
// ============================================================================

// Alternative approaches:
// 1. @types packages - Pre-built declarations
// 2. dts-gen - Automatic declaration generation
// 3. API Extractor - Library type extraction
// 4. tsd - Declaration testing
// 5. Manual declaration - Custom .d.ts files

// ============================================================================
// SECTION 14: CROSS-REFERENCE
// ============================================================================

// Related topics:
// - 03_DEVELOPMENT/02_TypeScript_Workspace/08_Declaration_Maps.ts
// - 01_FUNDAMENTALS/02_SYNTAX/10_Type_Directives/04_Custom_Type_Declarations.ts
// - 01_FUNDAMENTALS/02_SYNTAX/10_Type_Directives/05_Ambient_Declarations.ts
// - 03_DEVELOPMENT/04_Debugging_Tools/06_Type_Inspector.ts

console.log("\n=== Declaration Files Complete ===");
console.log("Next: FUNDAMENTALS/DEVELOPMENT/03_Compiler_Options/01_Compiler_Flags");